"""Pydantic schemas used for websocket telemetry messages.

This module defines lightweight models sent over the websocket connection
for runtime telemetry: logs, metrics, hardware stats and overall status.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class LogMessage(BaseModel):
    """A single log entry emitted by a running job.

    Fields
    ------
    time:
        Human-readable time string in HH:MM:SS format generated by default.
    msg:
        The textual log message.
    type:
        Short label for the message category (e.g. 'default', 'error').
    epoch:
        Optional training epoch index associated with the log message.
    """

    time: str = Field(default_factory=lambda: datetime.now().strftime("%H:%M:%S"))
    msg: str
    type: str = "default"
    epoch: int | None = None


class MetricData(BaseModel):
    """Model for a single set of training metrics reported during a trial.

    Attributes
    ----------
    trial: int
        Trial number.
    loss: float | None
        Training loss.
    r2: float | None
        R^2 metric for regression.
    mae: float | None
        Mean absolute error.
    val_loss: float | None
        Validation loss.
    """

    trial: int
    epoch: int | None = None
    loss: float | None = None
    r2: float | None = None
    mae: float | None = None
    val_loss: float | None = None


class HardwareStats(BaseModel):
    """Hardware usage snapshot reported by the worker process.

    All fields are optional and measured at the time of the report.
    """

    vram_total_gb: float | None = None
    vram_used_gb: float | None = None
    vram_percent: int | None = None
    gpu_use_percent: int | None = None
    gpu_temp_c: int | None = None
    cpu_percent: float | None = None
    ram_used_gb: float | None = None
    ram_total_gb: float | None = None
    ram_percent: float | None = None


class ResultData(BaseModel):
    """Aggregate result metadata for a completed or running job.

    Currently only contains `best_r2`, but keeps the shape extensible.
    """

    best_r2: float | None = None


class StatusData(BaseModel):
    """Overall status message for a running job.

    Carries flags describing the run state as well as recent metrics,
    logs and hardware stats.
    """

    is_running: bool
    is_aborting: bool = False
    progress: int
    run_id: str | None = None
    current_trial: int
    total_trials: int
    result: ResultData | None = None
    metrics_history: list[MetricData] = []
    logs: list[LogMessage] = []
    hardware_stats: HardwareStats | None = None
    queue_size: int
    active_job_id: str | None = None


class TelemetryMessage(BaseModel):
    """Envelope for telemetry messages sent over the websocket connection.

    The `type` field determines how `data` should be interpreted by listeners.
    """

    type: str = Field(..., pattern="^(init|status|log|metrics|hardware|error)$")
    data: Any  # This will be validated dynamically based on `type`
